geocoder:
  build: geocoder
  ports:
    - "31010:31010"
  environment:
    GRASSHOPPER_ADDRESSPOINTS_HOST: points
    GRASSHOPPER_ADDRESSPOINTS_PORT: 8081
    GRASSHOPPER_CENSUS_HOST: lines
    GRASSHOPPER_CENSUS_PORT: 8082
    GRASSHOPPER_PARSER_HOST: parser
    GRASSHOPPER_PARSER_PORT: 5000

parser:
  build: ../grasshopper-parser
  ports:
    - "5000:5000"

loader:
  build: ../grasshopper-loader
  #command: ./grasshopper-loader.js -d test/data/new_york.json

# Must be named "elasticsearch" to create expected ELASTICSEARCH_* envvars
elasticsearch:
  image: elasticsearch:1.7.1

ui:
  build: ../grasshopper-ui
  ports:
    - "80:80"
